version: '3'

services:
  lambda:
    container_name: lambda
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: lambda-app
        target: /app
    env_file:
      - env/.env
    entrypoint: sh /tmp/entry.sh

volumes:
  lambda-app:
    name: lambda-app
    driver: local
    driver_opts:
      device: ./app
      type: none
      o: bind
